fix formatting in service.yaml
fix formatting in service.yaml. Was getting Release "dwn-server" does not exist. Installing it now.
Error: YAML parse error on dwn-server/templates/service.yaml: error converting YAML to JSON: yaml: line 4: did not find expected node content